#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_coal_web.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ENG_ECOAL_MASS_KPT")]
	public partial class eCoalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public eCoalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ENG_ECOAL_MASS_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public eCoalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eCoalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eCoalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eCoalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_getMenuProfile")]
		public ISingleResult<cusp_getMenuProfileResult> cusp_getMenuProfile([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PID", DbType="VarChar(50)")] string pID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID);
			return ((ISingleResult<cusp_getMenuProfileResult>)(result.ReturnValue));
		}
	}
	
	public partial class cusp_getMenuProfileResult
	{
		
		private int _ID;
		
		private System.Nullable<int> _ID_MENU;
		
		private System.Nullable<int> _PARENT_ID;
		
		private System.Nullable<int> _SORT_ORDER;
		
		private string _MENU_DESC;
		
		private string _MENU_PATH;
		
		private string _MENU_ICON;
		
		private System.Nullable<int> _ID_PROFILE;
		
		private string _PROFILE;
		
		private System.Nullable<bool> _C;
		
		private System.Nullable<bool> _R;
		
		private System.Nullable<bool> _U;
		
		private System.Nullable<bool> _D;
		
		public cusp_getMenuProfileResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MENU", DbType="Int")]
		public System.Nullable<int> ID_MENU
		{
			get
			{
				return this._ID_MENU;
			}
			set
			{
				if ((this._ID_MENU != value))
				{
					this._ID_MENU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Int")]
		public System.Nullable<int> PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORT_ORDER", DbType="Int")]
		public System.Nullable<int> SORT_ORDER
		{
			get
			{
				return this._SORT_ORDER;
			}
			set
			{
				if ((this._SORT_ORDER != value))
				{
					this._SORT_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_DESC", DbType="VarChar(100)")]
		public string MENU_DESC
		{
			get
			{
				return this._MENU_DESC;
			}
			set
			{
				if ((this._MENU_DESC != value))
				{
					this._MENU_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_PATH", DbType="VarChar(100)")]
		public string MENU_PATH
		{
			get
			{
				return this._MENU_PATH;
			}
			set
			{
				if ((this._MENU_PATH != value))
				{
					this._MENU_PATH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_ICON", DbType="VarChar(100)")]
		public string MENU_ICON
		{
			get
			{
				return this._MENU_ICON;
			}
			set
			{
				if ((this._MENU_ICON != value))
				{
					this._MENU_ICON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROFILE", DbType="Int")]
		public System.Nullable<int> ID_PROFILE
		{
			get
			{
				return this._ID_PROFILE;
			}
			set
			{
				if ((this._ID_PROFILE != value))
				{
					this._ID_PROFILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFILE", DbType="VarChar(50)")]
		public string PROFILE
		{
			get
			{
				return this._PROFILE;
			}
			set
			{
				if ((this._PROFILE != value))
				{
					this._PROFILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="Bit")]
		public System.Nullable<bool> C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this._C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Bit")]
		public System.Nullable<bool> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U", DbType="Bit")]
		public System.Nullable<bool> U
		{
			get
			{
				return this._U;
			}
			set
			{
				if ((this._U != value))
				{
					this._U = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Bit")]
		public System.Nullable<bool> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
