#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_coal_web.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ENG_ECOAL_MASS_KPT")]
	public partial class eCoalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_M_IMAGE(TBL_M_IMAGE instance);
    partial void UpdateTBL_M_IMAGE(TBL_M_IMAGE instance);
    partial void DeleteTBL_M_IMAGE(TBL_M_IMAGE instance);
    #endregion
		
		public eCoalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ENG_ECOAL_MASS_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public eCoalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eCoalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eCoalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public eCoalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_M_IMAGE> TBL_M_IMAGEs
		{
			get
			{
				return this.GetTable<TBL_M_IMAGE>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_getMenuProfile")]
		public ISingleResult<cusp_getMenuProfileResult> cusp_getMenuProfile([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PID", DbType="VarChar(50)")] string pID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID);
			return ((ISingleResult<cusp_getMenuProfileResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_IMAGE")]
	public partial class TBL_M_IMAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _IMAGE_TITLE;
		
		private System.Data.Linq.Binary _IMAGE_BYTE;
		
		private string _IMAGE_PATH;
		
		private string _DISTRICT;
		
		private System.Nullable<System.DateTime> _UPLOAD_DATE;
		
		private string _UPLOAD_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIMAGE_TITLEChanging(string value);
    partial void OnIMAGE_TITLEChanged();
    partial void OnIMAGE_BYTEChanging(System.Data.Linq.Binary value);
    partial void OnIMAGE_BYTEChanged();
    partial void OnIMAGE_PATHChanging(string value);
    partial void OnIMAGE_PATHChanged();
    partial void OnDISTRICTChanging(string value);
    partial void OnDISTRICTChanged();
    partial void OnUPLOAD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPLOAD_DATEChanged();
    partial void OnUPLOAD_BYChanging(string value);
    partial void OnUPLOAD_BYChanged();
    #endregion
		
		public TBL_M_IMAGE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE_TITLE", DbType="NVarChar(50)")]
		public string IMAGE_TITLE
		{
			get
			{
				return this._IMAGE_TITLE;
			}
			set
			{
				if ((this._IMAGE_TITLE != value))
				{
					this.OnIMAGE_TITLEChanging(value);
					this.SendPropertyChanging();
					this._IMAGE_TITLE = value;
					this.SendPropertyChanged("IMAGE_TITLE");
					this.OnIMAGE_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE_BYTE", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary IMAGE_BYTE
		{
			get
			{
				return this._IMAGE_BYTE;
			}
			set
			{
				if ((this._IMAGE_BYTE != value))
				{
					this.OnIMAGE_BYTEChanging(value);
					this.SendPropertyChanging();
					this._IMAGE_BYTE = value;
					this.SendPropertyChanged("IMAGE_BYTE");
					this.OnIMAGE_BYTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE_PATH", DbType="NVarChar(50)")]
		public string IMAGE_PATH
		{
			get
			{
				return this._IMAGE_PATH;
			}
			set
			{
				if ((this._IMAGE_PATH != value))
				{
					this.OnIMAGE_PATHChanging(value);
					this.SendPropertyChanging();
					this._IMAGE_PATH = value;
					this.SendPropertyChanged("IMAGE_PATH");
					this.OnIMAGE_PATHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(5)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this.OnDISTRICTChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT = value;
					this.SendPropertyChanged("DISTRICT");
					this.OnDISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPLOAD_DATE
		{
			get
			{
				return this._UPLOAD_DATE;
			}
			set
			{
				if ((this._UPLOAD_DATE != value))
				{
					this.OnUPLOAD_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD_DATE = value;
					this.SendPropertyChanged("UPLOAD_DATE");
					this.OnUPLOAD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_BY", DbType="VarChar(50)")]
		public string UPLOAD_BY
		{
			get
			{
				return this._UPLOAD_BY;
			}
			set
			{
				if ((this._UPLOAD_BY != value))
				{
					this.OnUPLOAD_BYChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD_BY = value;
					this.SendPropertyChanged("UPLOAD_BY");
					this.OnUPLOAD_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class cusp_getMenuProfileResult
	{
		
		private int _ID;
		
		private System.Nullable<int> _ID_MENU;
		
		private System.Nullable<int> _PARENT_ID;
		
		private System.Nullable<int> _SORT_ORDER;
		
		private string _MENU_DESC;
		
		private string _MENU_PATH;
		
		private string _MENU_ICON;
		
		private System.Nullable<int> _ID_PROFILE;
		
		private string _PROFILE;
		
		private System.Nullable<bool> _C;
		
		private System.Nullable<bool> _R;
		
		private System.Nullable<bool> _U;
		
		private System.Nullable<bool> _D;
		
		public cusp_getMenuProfileResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MENU", DbType="Int")]
		public System.Nullable<int> ID_MENU
		{
			get
			{
				return this._ID_MENU;
			}
			set
			{
				if ((this._ID_MENU != value))
				{
					this._ID_MENU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Int")]
		public System.Nullable<int> PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORT_ORDER", DbType="Int")]
		public System.Nullable<int> SORT_ORDER
		{
			get
			{
				return this._SORT_ORDER;
			}
			set
			{
				if ((this._SORT_ORDER != value))
				{
					this._SORT_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_DESC", DbType="VarChar(100)")]
		public string MENU_DESC
		{
			get
			{
				return this._MENU_DESC;
			}
			set
			{
				if ((this._MENU_DESC != value))
				{
					this._MENU_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_PATH", DbType="VarChar(100)")]
		public string MENU_PATH
		{
			get
			{
				return this._MENU_PATH;
			}
			set
			{
				if ((this._MENU_PATH != value))
				{
					this._MENU_PATH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_ICON", DbType="VarChar(100)")]
		public string MENU_ICON
		{
			get
			{
				return this._MENU_ICON;
			}
			set
			{
				if ((this._MENU_ICON != value))
				{
					this._MENU_ICON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROFILE", DbType="Int")]
		public System.Nullable<int> ID_PROFILE
		{
			get
			{
				return this._ID_PROFILE;
			}
			set
			{
				if ((this._ID_PROFILE != value))
				{
					this._ID_PROFILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFILE", DbType="VarChar(50)")]
		public string PROFILE
		{
			get
			{
				return this._PROFILE;
			}
			set
			{
				if ((this._PROFILE != value))
				{
					this._PROFILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="Bit")]
		public System.Nullable<bool> C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this._C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Bit")]
		public System.Nullable<bool> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U", DbType="Bit")]
		public System.Nullable<bool> U
		{
			get
			{
				return this._U;
			}
			set
			{
				if ((this._U != value))
				{
					this._U = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Bit")]
		public System.Nullable<bool> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
