#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_coal_api.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ENG_ECOAL_MASS_KPT")]
	public partial class db_eCoalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_M_PROFILE(TBL_M_PROFILE instance);
    partial void UpdateTBL_M_PROFILE(TBL_M_PROFILE instance);
    partial void DeleteTBL_M_PROFILE(TBL_M_PROFILE instance);
    partial void InsertTBL_M_PEKERJAAN(TBL_M_PEKERJAAN instance);
    partial void UpdateTBL_M_PEKERJAAN(TBL_M_PEKERJAAN instance);
    partial void DeleteTBL_M_PEKERJAAN(TBL_M_PEKERJAAN instance);
    partial void InsertTBL_T_PAIRING_OPERATOR_UNIT(TBL_T_PAIRING_OPERATOR_UNIT instance);
    partial void UpdateTBL_T_PAIRING_OPERATOR_UNIT(TBL_T_PAIRING_OPERATOR_UNIT instance);
    partial void DeleteTBL_T_PAIRING_OPERATOR_UNIT(TBL_T_PAIRING_OPERATOR_UNIT instance);
    partial void InsertTBL_T_APPRAISAL(TBL_T_APPRAISAL instance);
    partial void UpdateTBL_T_APPRAISAL(TBL_T_APPRAISAL instance);
    partial void DeleteTBL_T_APPRAISAL(TBL_T_APPRAISAL instance);
    partial void InsertTBL_M_GRADE(TBL_M_GRADE instance);
    partial void UpdateTBL_M_GRADE(TBL_M_GRADE instance);
    partial void DeleteTBL_M_GRADE(TBL_M_GRADE instance);
    partial void InsertTBL_M_SEAM(TBL_M_SEAM instance);
    partial void UpdateTBL_M_SEAM(TBL_M_SEAM instance);
    partial void DeleteTBL_M_SEAM(TBL_M_SEAM instance);
    partial void InsertTBL_T_IN_SITU(TBL_T_IN_SITU instance);
    partial void UpdateTBL_T_IN_SITU(TBL_T_IN_SITU instance);
    partial void DeleteTBL_T_IN_SITU(TBL_T_IN_SITU instance);
    partial void InsertTBL_T_REQUEST_COAL(TBL_T_REQUEST_COAL instance);
    partial void UpdateTBL_T_REQUEST_COAL(TBL_T_REQUEST_COAL instance);
    partial void DeleteTBL_T_REQUEST_COAL(TBL_T_REQUEST_COAL instance);
    partial void InsertTBL_M_OPERATOR_EX(TBL_M_OPERATOR_EX instance);
    partial void UpdateTBL_M_OPERATOR_EX(TBL_M_OPERATOR_EX instance);
    partial void DeleteTBL_M_OPERATOR_EX(TBL_M_OPERATOR_EX instance);
    partial void InsertTBL_M_JABATAN(TBL_M_JABATAN instance);
    partial void UpdateTBL_M_JABATAN(TBL_M_JABATAN instance);
    partial void DeleteTBL_M_JABATAN(TBL_M_JABATAN instance);
    partial void InsertTBL_M_SUBCONT(TBL_M_SUBCONT instance);
    partial void UpdateTBL_M_SUBCONT(TBL_M_SUBCONT instance);
    partial void DeleteTBL_M_SUBCONT(TBL_M_SUBCONT instance);
    partial void InsertTBL_M_LOCATION(TBL_M_LOCATION instance);
    partial void UpdateTBL_M_LOCATION(TBL_M_LOCATION instance);
    partial void DeleteTBL_M_LOCATION(TBL_M_LOCATION instance);
    partial void InsertTBL_M_USER(TBL_M_USER instance);
    partial void UpdateTBL_M_USER(TBL_M_USER instance);
    partial void DeleteTBL_M_USER(TBL_M_USER instance);
    #endregion
		
		public db_eCoalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ENG_ECOAL_MASS_KPTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public db_eCoalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_eCoalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_eCoalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public db_eCoalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_M_PROFILE> TBL_M_PROFILEs
		{
			get
			{
				return this.GetTable<TBL_M_PROFILE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_PEKERJAAN> TBL_M_PEKERJAANs
		{
			get
			{
				return this.GetTable<TBL_M_PEKERJAAN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_PAIRING_OPERATOR_UNIT> TBL_T_PAIRING_OPERATOR_UNITs
		{
			get
			{
				return this.GetTable<TBL_T_PAIRING_OPERATOR_UNIT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_APPRAISAL> TBL_T_APPRAISALs
		{
			get
			{
				return this.GetTable<TBL_T_APPRAISAL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_GRADE> TBL_M_GRADEs
		{
			get
			{
				return this.GetTable<TBL_M_GRADE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_SEAM> TBL_M_SEAMs
		{
			get
			{
				return this.GetTable<TBL_M_SEAM>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_IN_SITU> TBL_T_IN_SITUs
		{
			get
			{
				return this.GetTable<TBL_T_IN_SITU>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_REQUEST_COAL> TBL_T_REQUEST_COALs
		{
			get
			{
				return this.GetTable<TBL_T_REQUEST_COAL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_OPERATOR_EX> TBL_M_OPERATOR_EXes
		{
			get
			{
				return this.GetTable<TBL_M_OPERATOR_EX>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_JABATAN> TBL_M_JABATANs
		{
			get
			{
				return this.GetTable<TBL_M_JABATAN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_SUBCONT> TBL_M_SUBCONTs
		{
			get
			{
				return this.GetTable<TBL_M_SUBCONT>();
			}
		}
		
		public System.Data.Linq.Table<VW_DEPT> VW_DEPTs
		{
			get
			{
				return this.GetTable<VW_DEPT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_LOCATION> TBL_M_LOCATIONs
		{
			get
			{
				return this.GetTable<TBL_M_LOCATION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_USER> TBL_M_USERs
		{
			get
			{
				return this.GetTable<TBL_M_USER>();
			}
		}
		
		public System.Data.Linq.Table<VW_USER_PROFILE> VW_USER_PROFILEs
		{
			get
			{
				return this.GetTable<VW_USER_PROFILE>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_getAlatByPekerjanSeam", IsComposable=true)]
		public IQueryable<cufn_getAlatByPekerjanSeamResult> cufn_getAlatByPekerjanSeam([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PEKERJAAN", DbType="Int")] System.Nullable<int> pEKERJAAN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEAM", DbType="Int")] System.Nullable<int> sEAM)
		{
			return this.CreateMethodCallQuery<cufn_getAlatByPekerjanSeamResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pEKERJAAN, sEAM);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_getListOperatorByRating", IsComposable=true)]
		public IQueryable<cufn_getListOperatorByRatingResult> cufn_getListOperatorByRating([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PEKERJAAN", DbType="Int")] System.Nullable<int> pEKERJAAN)
		{
			return this.CreateMethodCallQuery<cufn_getListOperatorByRatingResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pEKERJAAN);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cusp_getListPenilaian")]
		public ISingleResult<cusp_getListPenilaianResult> cusp_getListPenilaian()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cusp_getListPenilaianResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_getDetailOperator", IsComposable=true)]
		public IQueryable<cufn_getDetailOperatorResult> cufn_getDetailOperator([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return this.CreateMethodCallQuery<cufn_getDetailOperatorResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_PROFILE")]
	public partial class TBL_M_PROFILE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _PROFILE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPROFILEChanging(string value);
    partial void OnPROFILEChanged();
    #endregion
		
		public TBL_M_PROFILE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFILE", DbType="VarChar(50)")]
		public string PROFILE
		{
			get
			{
				return this._PROFILE;
			}
			set
			{
				if ((this._PROFILE != value))
				{
					this.OnPROFILEChanging(value);
					this.SendPropertyChanging();
					this._PROFILE = value;
					this.SendPropertyChanged("PROFILE");
					this.OnPROFILEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_PEKERJAAN")]
	public partial class TBL_M_PEKERJAAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _NAMA_PEKERJAAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNAMA_PEKERJAANChanging(string value);
    partial void OnNAMA_PEKERJAANChanged();
    #endregion
		
		public TBL_M_PEKERJAAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PEKERJAAN", DbType="VarChar(50)")]
		public string NAMA_PEKERJAAN
		{
			get
			{
				return this._NAMA_PEKERJAAN;
			}
			set
			{
				if ((this._NAMA_PEKERJAAN != value))
				{
					this.OnNAMA_PEKERJAANChanging(value);
					this.SendPropertyChanging();
					this._NAMA_PEKERJAAN = value;
					this.SendPropertyChanged("NAMA_PEKERJAAN");
					this.OnNAMA_PEKERJAANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_PAIRING_OPERATOR_UNIT")]
	public partial class TBL_T_PAIRING_OPERATOR_UNIT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _OPERATOR;
		
		private System.Nullable<int> _ID_EQUIPMENT;
		
		private string _EQUIPMENT;
		
		private System.Nullable<int> _ID_PEKERJAAN;
		
		private System.Nullable<int> _ID_SEAM;
		
		private System.Nullable<decimal> _VOLUME;
		
		private System.Nullable<System.DateTime> _START_WORK_HOUR;
		
		private System.Nullable<int> _TIME_H;
		
		private System.Nullable<int> _TIME_M;
		
		private System.Nullable<int> _TIME_S;
		
		private string _GRADE;
		
		private System.Nullable<System.DateTime> _INPUT_DATE;
		
		private string _INPUT_BY;
		
		private System.Nullable<int> _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOPERATORChanging(string value);
    partial void OnOPERATORChanged();
    partial void OnID_EQUIPMENTChanging(System.Nullable<int> value);
    partial void OnID_EQUIPMENTChanged();
    partial void OnEQUIPMENTChanging(string value);
    partial void OnEQUIPMENTChanged();
    partial void OnID_PEKERJAANChanging(System.Nullable<int> value);
    partial void OnID_PEKERJAANChanged();
    partial void OnID_SEAMChanging(System.Nullable<int> value);
    partial void OnID_SEAMChanged();
    partial void OnVOLUMEChanging(System.Nullable<decimal> value);
    partial void OnVOLUMEChanged();
    partial void OnSTART_WORK_HOURChanging(System.Nullable<System.DateTime> value);
    partial void OnSTART_WORK_HOURChanged();
    partial void OnTIME_HChanging(System.Nullable<int> value);
    partial void OnTIME_HChanged();
    partial void OnTIME_MChanging(System.Nullable<int> value);
    partial void OnTIME_MChanged();
    partial void OnTIME_SChanging(System.Nullable<int> value);
    partial void OnTIME_SChanged();
    partial void OnGRADEChanging(string value);
    partial void OnGRADEChanged();
    partial void OnINPUT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnINPUT_DATEChanged();
    partial void OnINPUT_BYChanging(string value);
    partial void OnINPUT_BYChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    #endregion
		
		public TBL_T_PAIRING_OPERATOR_UNIT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATOR", DbType="VarChar(20)")]
		public string OPERATOR
		{
			get
			{
				return this._OPERATOR;
			}
			set
			{
				if ((this._OPERATOR != value))
				{
					this.OnOPERATORChanging(value);
					this.SendPropertyChanging();
					this._OPERATOR = value;
					this.SendPropertyChanged("OPERATOR");
					this.OnOPERATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EQUIPMENT", DbType="Int")]
		public System.Nullable<int> ID_EQUIPMENT
		{
			get
			{
				return this._ID_EQUIPMENT;
			}
			set
			{
				if ((this._ID_EQUIPMENT != value))
				{
					this.OnID_EQUIPMENTChanging(value);
					this.SendPropertyChanging();
					this._ID_EQUIPMENT = value;
					this.SendPropertyChanged("ID_EQUIPMENT");
					this.OnID_EQUIPMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT", DbType="VarChar(50)")]
		public string EQUIPMENT
		{
			get
			{
				return this._EQUIPMENT;
			}
			set
			{
				if ((this._EQUIPMENT != value))
				{
					this.OnEQUIPMENTChanging(value);
					this.SendPropertyChanging();
					this._EQUIPMENT = value;
					this.SendPropertyChanged("EQUIPMENT");
					this.OnEQUIPMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEKERJAAN", DbType="Int")]
		public System.Nullable<int> ID_PEKERJAAN
		{
			get
			{
				return this._ID_PEKERJAAN;
			}
			set
			{
				if ((this._ID_PEKERJAAN != value))
				{
					this.OnID_PEKERJAANChanging(value);
					this.SendPropertyChanging();
					this._ID_PEKERJAAN = value;
					this.SendPropertyChanged("ID_PEKERJAAN");
					this.OnID_PEKERJAANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SEAM", DbType="Int")]
		public System.Nullable<int> ID_SEAM
		{
			get
			{
				return this._ID_SEAM;
			}
			set
			{
				if ((this._ID_SEAM != value))
				{
					this.OnID_SEAMChanging(value);
					this.SendPropertyChanging();
					this._ID_SEAM = value;
					this.SendPropertyChanged("ID_SEAM");
					this.OnID_SEAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOLUME", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> VOLUME
		{
			get
			{
				return this._VOLUME;
			}
			set
			{
				if ((this._VOLUME != value))
				{
					this.OnVOLUMEChanging(value);
					this.SendPropertyChanging();
					this._VOLUME = value;
					this.SendPropertyChanged("VOLUME");
					this.OnVOLUMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_WORK_HOUR", DbType="DateTime")]
		public System.Nullable<System.DateTime> START_WORK_HOUR
		{
			get
			{
				return this._START_WORK_HOUR;
			}
			set
			{
				if ((this._START_WORK_HOUR != value))
				{
					this.OnSTART_WORK_HOURChanging(value);
					this.SendPropertyChanging();
					this._START_WORK_HOUR = value;
					this.SendPropertyChanged("START_WORK_HOUR");
					this.OnSTART_WORK_HOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_H", DbType="Int")]
		public System.Nullable<int> TIME_H
		{
			get
			{
				return this._TIME_H;
			}
			set
			{
				if ((this._TIME_H != value))
				{
					this.OnTIME_HChanging(value);
					this.SendPropertyChanging();
					this._TIME_H = value;
					this.SendPropertyChanged("TIME_H");
					this.OnTIME_HChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_M", DbType="Int")]
		public System.Nullable<int> TIME_M
		{
			get
			{
				return this._TIME_M;
			}
			set
			{
				if ((this._TIME_M != value))
				{
					this.OnTIME_MChanging(value);
					this.SendPropertyChanging();
					this._TIME_M = value;
					this.SendPropertyChanged("TIME_M");
					this.OnTIME_MChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_S", DbType="Int")]
		public System.Nullable<int> TIME_S
		{
			get
			{
				return this._TIME_S;
			}
			set
			{
				if ((this._TIME_S != value))
				{
					this.OnTIME_SChanging(value);
					this.SendPropertyChanging();
					this._TIME_S = value;
					this.SendPropertyChanged("TIME_S");
					this.OnTIME_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADE", DbType="VarChar(5)")]
		public string GRADE
		{
			get
			{
				return this._GRADE;
			}
			set
			{
				if ((this._GRADE != value))
				{
					this.OnGRADEChanging(value);
					this.SendPropertyChanging();
					this._GRADE = value;
					this.SendPropertyChanged("GRADE");
					this.OnGRADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> INPUT_DATE
		{
			get
			{
				return this._INPUT_DATE;
			}
			set
			{
				if ((this._INPUT_DATE != value))
				{
					this.OnINPUT_DATEChanging(value);
					this.SendPropertyChanging();
					this._INPUT_DATE = value;
					this.SendPropertyChanged("INPUT_DATE");
					this.OnINPUT_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_BY", DbType="VarChar(50)")]
		public string INPUT_BY
		{
			get
			{
				return this._INPUT_BY;
			}
			set
			{
				if ((this._INPUT_BY != value))
				{
					this.OnINPUT_BYChanging(value);
					this.SendPropertyChanging();
					this._INPUT_BY = value;
					this.SendPropertyChanged("INPUT_BY");
					this.OnINPUT_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_APPRAISAL")]
	public partial class TBL_T_APPRAISAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _PAIRING_OU_ID;
		
		private string _OPERATOR;
		
		private System.Nullable<decimal> _SAFETY;
		
		private System.Nullable<decimal> _KOMUNIKASI;
		
		private System.Nullable<decimal> _METODE_KERJA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPAIRING_OU_IDChanging(System.Nullable<int> value);
    partial void OnPAIRING_OU_IDChanged();
    partial void OnOPERATORChanging(string value);
    partial void OnOPERATORChanged();
    partial void OnSAFETYChanging(System.Nullable<decimal> value);
    partial void OnSAFETYChanged();
    partial void OnKOMUNIKASIChanging(System.Nullable<decimal> value);
    partial void OnKOMUNIKASIChanged();
    partial void OnMETODE_KERJAChanging(System.Nullable<decimal> value);
    partial void OnMETODE_KERJAChanged();
    #endregion
		
		public TBL_T_APPRAISAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAIRING_OU_ID", DbType="Int")]
		public System.Nullable<int> PAIRING_OU_ID
		{
			get
			{
				return this._PAIRING_OU_ID;
			}
			set
			{
				if ((this._PAIRING_OU_ID != value))
				{
					this.OnPAIRING_OU_IDChanging(value);
					this.SendPropertyChanging();
					this._PAIRING_OU_ID = value;
					this.SendPropertyChanged("PAIRING_OU_ID");
					this.OnPAIRING_OU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATOR", DbType="VarChar(50)")]
		public string OPERATOR
		{
			get
			{
				return this._OPERATOR;
			}
			set
			{
				if ((this._OPERATOR != value))
				{
					this.OnOPERATORChanging(value);
					this.SendPropertyChanging();
					this._OPERATOR = value;
					this.SendPropertyChanged("OPERATOR");
					this.OnOPERATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAFETY", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SAFETY
		{
			get
			{
				return this._SAFETY;
			}
			set
			{
				if ((this._SAFETY != value))
				{
					this.OnSAFETYChanging(value);
					this.SendPropertyChanging();
					this._SAFETY = value;
					this.SendPropertyChanged("SAFETY");
					this.OnSAFETYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOMUNIKASI", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> KOMUNIKASI
		{
			get
			{
				return this._KOMUNIKASI;
			}
			set
			{
				if ((this._KOMUNIKASI != value))
				{
					this.OnKOMUNIKASIChanging(value);
					this.SendPropertyChanging();
					this._KOMUNIKASI = value;
					this.SendPropertyChanged("KOMUNIKASI");
					this.OnKOMUNIKASIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_METODE_KERJA", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> METODE_KERJA
		{
			get
			{
				return this._METODE_KERJA;
			}
			set
			{
				if ((this._METODE_KERJA != value))
				{
					this.OnMETODE_KERJAChanging(value);
					this.SendPropertyChanging();
					this._METODE_KERJA = value;
					this.SendPropertyChanged("METODE_KERJA");
					this.OnMETODE_KERJAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_GRADE")]
	public partial class TBL_M_GRADE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GRADE;
		
		private System.Nullable<int> _GAR_MIN;
		
		private System.Nullable<int> _GAR_MAX;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGRADEChanging(string value);
    partial void OnGRADEChanged();
    partial void OnGAR_MINChanging(System.Nullable<int> value);
    partial void OnGAR_MINChanged();
    partial void OnGAR_MAXChanging(System.Nullable<int> value);
    partial void OnGAR_MAXChanged();
    #endregion
		
		public TBL_M_GRADE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GRADE
		{
			get
			{
				return this._GRADE;
			}
			set
			{
				if ((this._GRADE != value))
				{
					this.OnGRADEChanging(value);
					this.SendPropertyChanging();
					this._GRADE = value;
					this.SendPropertyChanged("GRADE");
					this.OnGRADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GAR_MIN", DbType="Int")]
		public System.Nullable<int> GAR_MIN
		{
			get
			{
				return this._GAR_MIN;
			}
			set
			{
				if ((this._GAR_MIN != value))
				{
					this.OnGAR_MINChanging(value);
					this.SendPropertyChanging();
					this._GAR_MIN = value;
					this.SendPropertyChanged("GAR_MIN");
					this.OnGAR_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GAR_MAX", DbType="Int")]
		public System.Nullable<int> GAR_MAX
		{
			get
			{
				return this._GAR_MAX;
			}
			set
			{
				if ((this._GAR_MAX != value))
				{
					this.OnGAR_MAXChanging(value);
					this.SendPropertyChanging();
					this._GAR_MAX = value;
					this.SendPropertyChanged("GAR_MAX");
					this.OnGAR_MAXChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_SEAM")]
	public partial class TBL_M_SEAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _NAMA_SEAM;
		
		private string _GRADE;
		
		private string _INITIAL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNAMA_SEAMChanging(string value);
    partial void OnNAMA_SEAMChanged();
    partial void OnGRADEChanging(string value);
    partial void OnGRADEChanged();
    partial void OnINITIALChanging(string value);
    partial void OnINITIALChanged();
    #endregion
		
		public TBL_M_SEAM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_SEAM", DbType="VarChar(50)")]
		public string NAMA_SEAM
		{
			get
			{
				return this._NAMA_SEAM;
			}
			set
			{
				if ((this._NAMA_SEAM != value))
				{
					this.OnNAMA_SEAMChanging(value);
					this.SendPropertyChanging();
					this._NAMA_SEAM = value;
					this.SendPropertyChanged("NAMA_SEAM");
					this.OnNAMA_SEAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADE", DbType="VarChar(50)")]
		public string GRADE
		{
			get
			{
				return this._GRADE;
			}
			set
			{
				if ((this._GRADE != value))
				{
					this.OnGRADEChanging(value);
					this.SendPropertyChanging();
					this._GRADE = value;
					this.SendPropertyChanged("GRADE");
					this.OnGRADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INITIAL", DbType="VarChar(50)")]
		public string INITIAL
		{
			get
			{
				return this._INITIAL;
			}
			set
			{
				if ((this._INITIAL != value))
				{
					this.OnINITIALChanging(value);
					this.SendPropertyChanging();
					this._INITIAL = value;
					this.SendPropertyChanged("INITIAL");
					this.OnINITIALChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_IN_SITU")]
	public partial class TBL_T_IN_SITU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_IN_SITU;
		
		private System.Nullable<int> _ID_SEAM;
		
		private string _GRADE;
		
		private System.Nullable<decimal> _GAR_ACTUAL;
		
		private string _COAL_CONDITION;
		
		private System.Nullable<decimal> _TOTAL_TONASE;
		
		private System.Nullable<System.DateTime> _TANGGAL;
		
		private System.Nullable<System.DateTime> _INPUT_DATE;
		
		private string _INPUT_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_IN_SITUChanging(string value);
    partial void OnID_IN_SITUChanged();
    partial void OnID_SEAMChanging(System.Nullable<int> value);
    partial void OnID_SEAMChanged();
    partial void OnGRADEChanging(string value);
    partial void OnGRADEChanged();
    partial void OnGAR_ACTUALChanging(System.Nullable<decimal> value);
    partial void OnGAR_ACTUALChanged();
    partial void OnCOAL_CONDITIONChanging(string value);
    partial void OnCOAL_CONDITIONChanged();
    partial void OnTOTAL_TONASEChanging(System.Nullable<decimal> value);
    partial void OnTOTAL_TONASEChanged();
    partial void OnTANGGALChanging(System.Nullable<System.DateTime> value);
    partial void OnTANGGALChanged();
    partial void OnINPUT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnINPUT_DATEChanged();
    partial void OnINPUT_BYChanging(string value);
    partial void OnINPUT_BYChanged();
    #endregion
		
		public TBL_T_IN_SITU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_IN_SITU", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_IN_SITU
		{
			get
			{
				return this._ID_IN_SITU;
			}
			set
			{
				if ((this._ID_IN_SITU != value))
				{
					this.OnID_IN_SITUChanging(value);
					this.SendPropertyChanging();
					this._ID_IN_SITU = value;
					this.SendPropertyChanged("ID_IN_SITU");
					this.OnID_IN_SITUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SEAM", DbType="Int")]
		public System.Nullable<int> ID_SEAM
		{
			get
			{
				return this._ID_SEAM;
			}
			set
			{
				if ((this._ID_SEAM != value))
				{
					this.OnID_SEAMChanging(value);
					this.SendPropertyChanging();
					this._ID_SEAM = value;
					this.SendPropertyChanged("ID_SEAM");
					this.OnID_SEAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADE", DbType="VarChar(5)")]
		public string GRADE
		{
			get
			{
				return this._GRADE;
			}
			set
			{
				if ((this._GRADE != value))
				{
					this.OnGRADEChanging(value);
					this.SendPropertyChanging();
					this._GRADE = value;
					this.SendPropertyChanged("GRADE");
					this.OnGRADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GAR_ACTUAL", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GAR_ACTUAL
		{
			get
			{
				return this._GAR_ACTUAL;
			}
			set
			{
				if ((this._GAR_ACTUAL != value))
				{
					this.OnGAR_ACTUALChanging(value);
					this.SendPropertyChanging();
					this._GAR_ACTUAL = value;
					this.SendPropertyChanged("GAR_ACTUAL");
					this.OnGAR_ACTUALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COAL_CONDITION", DbType="VarChar(50)")]
		public string COAL_CONDITION
		{
			get
			{
				return this._COAL_CONDITION;
			}
			set
			{
				if ((this._COAL_CONDITION != value))
				{
					this.OnCOAL_CONDITIONChanging(value);
					this.SendPropertyChanging();
					this._COAL_CONDITION = value;
					this.SendPropertyChanged("COAL_CONDITION");
					this.OnCOAL_CONDITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_TONASE", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TOTAL_TONASE
		{
			get
			{
				return this._TOTAL_TONASE;
			}
			set
			{
				if ((this._TOTAL_TONASE != value))
				{
					this.OnTOTAL_TONASEChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_TONASE = value;
					this.SendPropertyChanged("TOTAL_TONASE");
					this.OnTOTAL_TONASEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANGGAL", DbType="Date")]
		public System.Nullable<System.DateTime> TANGGAL
		{
			get
			{
				return this._TANGGAL;
			}
			set
			{
				if ((this._TANGGAL != value))
				{
					this.OnTANGGALChanging(value);
					this.SendPropertyChanging();
					this._TANGGAL = value;
					this.SendPropertyChanged("TANGGAL");
					this.OnTANGGALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> INPUT_DATE
		{
			get
			{
				return this._INPUT_DATE;
			}
			set
			{
				if ((this._INPUT_DATE != value))
				{
					this.OnINPUT_DATEChanging(value);
					this.SendPropertyChanging();
					this._INPUT_DATE = value;
					this.SendPropertyChanged("INPUT_DATE");
					this.OnINPUT_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_BY", DbType="VarChar(50)")]
		public string INPUT_BY
		{
			get
			{
				return this._INPUT_BY;
			}
			set
			{
				if ((this._INPUT_BY != value))
				{
					this.OnINPUT_BYChanging(value);
					this.SendPropertyChanging();
					this._INPUT_BY = value;
					this.SendPropertyChanged("INPUT_BY");
					this.OnINPUT_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_REQUEST_COAL")]
	public partial class TBL_T_REQUEST_COAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MOMCOST;
		
		private System.Nullable<decimal> _VOLUMECOAL;
		
		private System.Nullable<decimal> _TARGETGCV;
		
		private System.Nullable<System.DateTime> _DEADLINE;
		
		private string _INPUT_DATE;
		
		private string _INPUT_BY;
		
		private string _DISTRICT;
		
		private System.Nullable<int> _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMOMCOSTChanging(string value);
    partial void OnMOMCOSTChanged();
    partial void OnVOLUMECOALChanging(System.Nullable<decimal> value);
    partial void OnVOLUMECOALChanged();
    partial void OnTARGETGCVChanging(System.Nullable<decimal> value);
    partial void OnTARGETGCVChanged();
    partial void OnDEADLINEChanging(System.Nullable<System.DateTime> value);
    partial void OnDEADLINEChanged();
    partial void OnINPUT_DATEChanging(string value);
    partial void OnINPUT_DATEChanged();
    partial void OnINPUT_BYChanging(string value);
    partial void OnINPUT_BYChanged();
    partial void OnDISTRICTChanging(string value);
    partial void OnDISTRICTChanged();
    partial void OnFLAGChanging(System.Nullable<int> value);
    partial void OnFLAGChanged();
    #endregion
		
		public TBL_T_REQUEST_COAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOMCOST", DbType="VarChar(50)")]
		public string MOMCOST
		{
			get
			{
				return this._MOMCOST;
			}
			set
			{
				if ((this._MOMCOST != value))
				{
					this.OnMOMCOSTChanging(value);
					this.SendPropertyChanging();
					this._MOMCOST = value;
					this.SendPropertyChanged("MOMCOST");
					this.OnMOMCOSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOLUMECOAL", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> VOLUMECOAL
		{
			get
			{
				return this._VOLUMECOAL;
			}
			set
			{
				if ((this._VOLUMECOAL != value))
				{
					this.OnVOLUMECOALChanging(value);
					this.SendPropertyChanging();
					this._VOLUMECOAL = value;
					this.SendPropertyChanged("VOLUMECOAL");
					this.OnVOLUMECOALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARGETGCV", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TARGETGCV
		{
			get
			{
				return this._TARGETGCV;
			}
			set
			{
				if ((this._TARGETGCV != value))
				{
					this.OnTARGETGCVChanging(value);
					this.SendPropertyChanging();
					this._TARGETGCV = value;
					this.SendPropertyChanged("TARGETGCV");
					this.OnTARGETGCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEADLINE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DEADLINE
		{
			get
			{
				return this._DEADLINE;
			}
			set
			{
				if ((this._DEADLINE != value))
				{
					this.OnDEADLINEChanging(value);
					this.SendPropertyChanging();
					this._DEADLINE = value;
					this.SendPropertyChanged("DEADLINE");
					this.OnDEADLINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_DATE", DbType="VarChar(50)")]
		public string INPUT_DATE
		{
			get
			{
				return this._INPUT_DATE;
			}
			set
			{
				if ((this._INPUT_DATE != value))
				{
					this.OnINPUT_DATEChanging(value);
					this.SendPropertyChanging();
					this._INPUT_DATE = value;
					this.SendPropertyChanged("INPUT_DATE");
					this.OnINPUT_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_BY", DbType="VarChar(50)")]
		public string INPUT_BY
		{
			get
			{
				return this._INPUT_BY;
			}
			set
			{
				if ((this._INPUT_BY != value))
				{
					this.OnINPUT_BYChanging(value);
					this.SendPropertyChanging();
					this._INPUT_BY = value;
					this.SendPropertyChanged("INPUT_BY");
					this.OnINPUT_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(50)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this.OnDISTRICTChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT = value;
					this.SendPropertyChanged("DISTRICT");
					this.OnDISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_OPERATOR_EX")]
	public partial class TBL_M_OPERATOR_EX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NRP;
		
		private string _NAMA;
		
		private string _SUBCONT_CODE;
		
		private System.Nullable<int> _ID_JABATAN;
		
		private string _DEPT_CODE;
		
		private string _DISTRICT;
		
		private System.Nullable<System.DateTime> _TGL_MASUK;
		
		private System.Nullable<System.DateTime> _INPUT_DATE;
		
		private string _INPUT_BY;
		
		private System.Nullable<int> _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnSUBCONT_CODEChanging(string value);
    partial void OnSUBCONT_CODEChanged();
    partial void OnID_JABATANChanging(System.Nullable<int> value);
    partial void OnID_JABATANChanged();
    partial void OnDEPT_CODEChanging(string value);
    partial void OnDEPT_CODEChanged();
    partial void OnDISTRICTChanging(string value);
    partial void OnDISTRICTChanged();
    partial void OnTGL_MASUKChanging(System.Nullable<System.DateTime> value);
    partial void OnTGL_MASUKChanged();
    partial void OnINPUT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnINPUT_DATEChanged();
    partial void OnINPUT_BYChanging(string value);
    partial void OnINPUT_BYChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    #endregion
		
		public TBL_M_OPERATOR_EX()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(150)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBCONT_CODE", DbType="VarChar(5)")]
		public string SUBCONT_CODE
		{
			get
			{
				return this._SUBCONT_CODE;
			}
			set
			{
				if ((this._SUBCONT_CODE != value))
				{
					this.OnSUBCONT_CODEChanging(value);
					this.SendPropertyChanging();
					this._SUBCONT_CODE = value;
					this.SendPropertyChanged("SUBCONT_CODE");
					this.OnSUBCONT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_JABATAN", DbType="Int")]
		public System.Nullable<int> ID_JABATAN
		{
			get
			{
				return this._ID_JABATAN;
			}
			set
			{
				if ((this._ID_JABATAN != value))
				{
					this.OnID_JABATANChanging(value);
					this.SendPropertyChanging();
					this._ID_JABATAN = value;
					this.SendPropertyChanged("ID_JABATAN");
					this.OnID_JABATANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(50)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this.OnDEPT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEPT_CODE = value;
					this.SendPropertyChanged("DEPT_CODE");
					this.OnDEPT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(5)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this.OnDISTRICTChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT = value;
					this.SendPropertyChanged("DISTRICT");
					this.OnDISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGL_MASUK", DbType="Date")]
		public System.Nullable<System.DateTime> TGL_MASUK
		{
			get
			{
				return this._TGL_MASUK;
			}
			set
			{
				if ((this._TGL_MASUK != value))
				{
					this.OnTGL_MASUKChanging(value);
					this.SendPropertyChanging();
					this._TGL_MASUK = value;
					this.SendPropertyChanged("TGL_MASUK");
					this.OnTGL_MASUKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> INPUT_DATE
		{
			get
			{
				return this._INPUT_DATE;
			}
			set
			{
				if ((this._INPUT_DATE != value))
				{
					this.OnINPUT_DATEChanging(value);
					this.SendPropertyChanging();
					this._INPUT_DATE = value;
					this.SendPropertyChanged("INPUT_DATE");
					this.OnINPUT_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INPUT_BY", DbType="VarChar(50)")]
		public string INPUT_BY
		{
			get
			{
				return this._INPUT_BY;
			}
			set
			{
				if ((this._INPUT_BY != value))
				{
					this.OnINPUT_BYChanging(value);
					this.SendPropertyChanging();
					this._INPUT_BY = value;
					this.SendPropertyChanged("INPUT_BY");
					this.OnINPUT_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_JABATAN")]
	public partial class TBL_M_JABATAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_JABATAN;
		
		private string _JABATAN;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private string _CREATE_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_JABATANChanging(int value);
    partial void OnID_JABATANChanged();
    partial void OnJABATANChanging(string value);
    partial void OnJABATANChanged();
    partial void OnCREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATEChanged();
    partial void OnCREATE_BYChanging(string value);
    partial void OnCREATE_BYChanged();
    #endregion
		
		public TBL_M_JABATAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_JABATAN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_JABATAN
		{
			get
			{
				return this._ID_JABATAN;
			}
			set
			{
				if ((this._ID_JABATAN != value))
				{
					this.OnID_JABATANChanging(value);
					this.SendPropertyChanging();
					this._ID_JABATAN = value;
					this.SendPropertyChanged("ID_JABATAN");
					this.OnID_JABATANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JABATAN", DbType="VarChar(100)")]
		public string JABATAN
		{
			get
			{
				return this._JABATAN;
			}
			set
			{
				if ((this._JABATAN != value))
				{
					this.OnJABATANChanging(value);
					this.SendPropertyChanging();
					this._JABATAN = value;
					this.SendPropertyChanged("JABATAN");
					this.OnJABATANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_BY", DbType="VarChar(50)")]
		public string CREATE_BY
		{
			get
			{
				return this._CREATE_BY;
			}
			set
			{
				if ((this._CREATE_BY != value))
				{
					this.OnCREATE_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATE_BY = value;
					this.SendPropertyChanged("CREATE_BY");
					this.OnCREATE_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_SUBCONT")]
	public partial class TBL_M_SUBCONT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SUBCONT_CODE;
		
		private string _SUBCONT_NAME;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private string _CRETATE_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSUBCONT_CODEChanging(string value);
    partial void OnSUBCONT_CODEChanged();
    partial void OnSUBCONT_NAMEChanging(string value);
    partial void OnSUBCONT_NAMEChanged();
    partial void OnCREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATEChanged();
    partial void OnCRETATE_BYChanging(string value);
    partial void OnCRETATE_BYChanged();
    #endregion
		
		public TBL_M_SUBCONT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBCONT_CODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SUBCONT_CODE
		{
			get
			{
				return this._SUBCONT_CODE;
			}
			set
			{
				if ((this._SUBCONT_CODE != value))
				{
					this.OnSUBCONT_CODEChanging(value);
					this.SendPropertyChanging();
					this._SUBCONT_CODE = value;
					this.SendPropertyChanged("SUBCONT_CODE");
					this.OnSUBCONT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBCONT_NAME", DbType="VarChar(150)")]
		public string SUBCONT_NAME
		{
			get
			{
				return this._SUBCONT_NAME;
			}
			set
			{
				if ((this._SUBCONT_NAME != value))
				{
					this.OnSUBCONT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SUBCONT_NAME = value;
					this.SendPropertyChanged("SUBCONT_NAME");
					this.OnSUBCONT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRETATE_BY", DbType="VarChar(50)")]
		public string CRETATE_BY
		{
			get
			{
				return this._CRETATE_BY;
			}
			set
			{
				if ((this._CRETATE_BY != value))
				{
					this.OnCRETATE_BYChanging(value);
					this.SendPropertyChanging();
					this._CRETATE_BY = value;
					this.SendPropertyChanged("CRETATE_BY");
					this.OnCRETATE_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DEPT")]
	public partial class VW_DEPT
	{
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _DSTRCT_CODE;
		
		public VW_DEPT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(100)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(100)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(100)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_LOCATION")]
	public partial class TBL_M_LOCATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOC;
		
		private string _LOCATION;
		
		private string _DISTRICT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOCChanging(int value);
    partial void OnID_LOCChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    partial void OnDISTRICTChanging(string value);
    partial void OnDISTRICTChanged();
    #endregion
		
		public TBL_M_LOCATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LOC
		{
			get
			{
				return this._ID_LOC;
			}
			set
			{
				if ((this._ID_LOC != value))
				{
					this.OnID_LOCChanging(value);
					this.SendPropertyChanging();
					this._ID_LOC = value;
					this.SendPropertyChanged("ID_LOC");
					this.OnID_LOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(50)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(50)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this.OnDISTRICTChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT = value;
					this.SendPropertyChanged("DISTRICT");
					this.OnDISTRICTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_USER")]
	public partial class TBL_M_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NRP;
		
		private System.Nullable<int> _ID_PROFILE;
		
		private string _DISTRICT;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private System.Nullable<System.DateTime> _CRETAE_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnID_PROFILEChanging(System.Nullable<int> value);
    partial void OnID_PROFILEChanged();
    partial void OnDISTRICTChanging(string value);
    partial void OnDISTRICTChanged();
    partial void OnCREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATEChanged();
    partial void OnCRETAE_BYChanging(System.Nullable<System.DateTime> value);
    partial void OnCRETAE_BYChanged();
    #endregion
		
		public TBL_M_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROFILE", DbType="Int")]
		public System.Nullable<int> ID_PROFILE
		{
			get
			{
				return this._ID_PROFILE;
			}
			set
			{
				if ((this._ID_PROFILE != value))
				{
					this.OnID_PROFILEChanging(value);
					this.SendPropertyChanging();
					this._ID_PROFILE = value;
					this.SendPropertyChanged("ID_PROFILE");
					this.OnID_PROFILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(50)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this.OnDISTRICTChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT = value;
					this.SendPropertyChanged("DISTRICT");
					this.OnDISTRICTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRETAE_BY", DbType="DateTime")]
		public System.Nullable<System.DateTime> CRETAE_BY
		{
			get
			{
				return this._CRETAE_BY;
			}
			set
			{
				if ((this._CRETAE_BY != value))
				{
					this.OnCRETAE_BYChanging(value);
					this.SendPropertyChanging();
					this._CRETAE_BY = value;
					this.SendPropertyChanged("CRETAE_BY");
					this.OnCRETAE_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_USER_PROFILE")]
	public partial class VW_USER_PROFILE
	{
		
		private int _ID;
		
		private string _NRP;
		
		private string _NAME;
		
		private System.Nullable<int> _ID_PROFILE;
		
		private string _PROFILE;
		
		private string _DISTRICT;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private System.Nullable<System.DateTime> _CRETAE_BY;
		
		public VW_USER_PROFILE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(100)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROFILE", DbType="Int")]
		public System.Nullable<int> ID_PROFILE
		{
			get
			{
				return this._ID_PROFILE;
			}
			set
			{
				if ((this._ID_PROFILE != value))
				{
					this._ID_PROFILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFILE", DbType="VarChar(50)")]
		public string PROFILE
		{
			get
			{
				return this._PROFILE;
			}
			set
			{
				if ((this._PROFILE != value))
				{
					this._PROFILE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(50)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this._DISTRICT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(100)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(100)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this._CREATE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRETAE_BY", DbType="DateTime")]
		public System.Nullable<System.DateTime> CRETAE_BY
		{
			get
			{
				return this._CRETAE_BY;
			}
			set
			{
				if ((this._CRETAE_BY != value))
				{
					this._CRETAE_BY = value;
				}
			}
		}
	}
	
	public partial class cufn_getAlatByPekerjanSeamResult
	{
		
		private int _ID_MAPPING;
		
		private System.Nullable<int> _ID_SEAM;
		
		private string _NAMA_SEAM;
		
		private System.Nullable<int> _ID_ALAT;
		
		private string _NAMA_ALAT;
		
		private System.Nullable<int> _PROTY;
		
		public cufn_getAlatByPekerjanSeamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MAPPING", DbType="Int NOT NULL")]
		public int ID_MAPPING
		{
			get
			{
				return this._ID_MAPPING;
			}
			set
			{
				if ((this._ID_MAPPING != value))
				{
					this._ID_MAPPING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SEAM", DbType="Int")]
		public System.Nullable<int> ID_SEAM
		{
			get
			{
				return this._ID_SEAM;
			}
			set
			{
				if ((this._ID_SEAM != value))
				{
					this._ID_SEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_SEAM", DbType="VarChar(50)")]
		public string NAMA_SEAM
		{
			get
			{
				return this._NAMA_SEAM;
			}
			set
			{
				if ((this._NAMA_SEAM != value))
				{
					this._NAMA_SEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ALAT", DbType="Int")]
		public System.Nullable<int> ID_ALAT
		{
			get
			{
				return this._ID_ALAT;
			}
			set
			{
				if ((this._ID_ALAT != value))
				{
					this._ID_ALAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_ALAT", DbType="VarChar(100)")]
		public string NAMA_ALAT
		{
			get
			{
				return this._NAMA_ALAT;
			}
			set
			{
				if ((this._NAMA_ALAT != value))
				{
					this._NAMA_ALAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROTY", DbType="Int")]
		public System.Nullable<int> PROTY
		{
			get
			{
				return this._PROTY;
			}
			set
			{
				if ((this._PROTY != value))
				{
					this._PROTY = value;
				}
			}
		}
	}
	
	public partial class cufn_getListOperatorByRatingResult
	{
		
		private string _NRP;
		
		private string _NAMA;
		
		private string _SUBCONT_CODE;
		
		private System.Nullable<int> _ID_JABATAN;
		
		private string _JABATAN;
		
		private string _DISTRICT;
		
		private int _ID_PEKERJAAN;
		
		private string _NAMA_PEKERJAAN;
		
		private decimal _AVG_AP;
		
		private int _STATUS_AVALIABLE;
		
		public cufn_getListOperatorByRatingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(150)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBCONT_CODE", DbType="VarChar(5)")]
		public string SUBCONT_CODE
		{
			get
			{
				return this._SUBCONT_CODE;
			}
			set
			{
				if ((this._SUBCONT_CODE != value))
				{
					this._SUBCONT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_JABATAN", DbType="Int")]
		public System.Nullable<int> ID_JABATAN
		{
			get
			{
				return this._ID_JABATAN;
			}
			set
			{
				if ((this._ID_JABATAN != value))
				{
					this._ID_JABATAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JABATAN", DbType="VarChar(100)")]
		public string JABATAN
		{
			get
			{
				return this._JABATAN;
			}
			set
			{
				if ((this._JABATAN != value))
				{
					this._JABATAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT", DbType="VarChar(5)")]
		public string DISTRICT
		{
			get
			{
				return this._DISTRICT;
			}
			set
			{
				if ((this._DISTRICT != value))
				{
					this._DISTRICT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEKERJAAN", DbType="Int NOT NULL")]
		public int ID_PEKERJAAN
		{
			get
			{
				return this._ID_PEKERJAAN;
			}
			set
			{
				if ((this._ID_PEKERJAAN != value))
				{
					this._ID_PEKERJAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PEKERJAAN", DbType="VarChar(50)")]
		public string NAMA_PEKERJAAN
		{
			get
			{
				return this._NAMA_PEKERJAAN;
			}
			set
			{
				if ((this._NAMA_PEKERJAAN != value))
				{
					this._NAMA_PEKERJAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVG_AP", DbType="Decimal(38,6) NOT NULL")]
		public decimal AVG_AP
		{
			get
			{
				return this._AVG_AP;
			}
			set
			{
				if ((this._AVG_AP != value))
				{
					this._AVG_AP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_AVALIABLE", DbType="Int NOT NULL")]
		public int STATUS_AVALIABLE
		{
			get
			{
				return this._STATUS_AVALIABLE;
			}
			set
			{
				if ((this._STATUS_AVALIABLE != value))
				{
					this._STATUS_AVALIABLE = value;
				}
			}
		}
	}
	
	public partial class cusp_getListPenilaianResult
	{
		
		private System.Nullable<int> _ID;
		
		private string _OPERATOR;
		
		private string _NAMA;
		
		private System.Nullable<int> _ID_EQUIPMENT;
		
		private string _EQUIPMENT;
		
		private System.Nullable<int> _ID_PEKERJAAN;
		
		private string _PEKERJAAN;
		
		private System.Nullable<int> _ID_SEAM;
		
		private string _SEAM;
		
		private System.Nullable<decimal> _VOLUME;
		
		private System.Nullable<System.DateTime> _START_WORK_HOUR;
		
		private System.Nullable<int> _TIME_H;
		
		private System.Nullable<int> _TIME_M;
		
		private System.Nullable<int> _STATUS;
		
		private System.Nullable<decimal> _NILAI;
		
		public cusp_getListPenilaianResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATOR", DbType="VarChar(50)")]
		public string OPERATOR
		{
			get
			{
				return this._OPERATOR;
			}
			set
			{
				if ((this._OPERATOR != value))
				{
					this._OPERATOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(100)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EQUIPMENT", DbType="Int")]
		public System.Nullable<int> ID_EQUIPMENT
		{
			get
			{
				return this._ID_EQUIPMENT;
			}
			set
			{
				if ((this._ID_EQUIPMENT != value))
				{
					this._ID_EQUIPMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT", DbType="VarChar(50)")]
		public string EQUIPMENT
		{
			get
			{
				return this._EQUIPMENT;
			}
			set
			{
				if ((this._EQUIPMENT != value))
				{
					this._EQUIPMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEKERJAAN", DbType="Int")]
		public System.Nullable<int> ID_PEKERJAAN
		{
			get
			{
				return this._ID_PEKERJAAN;
			}
			set
			{
				if ((this._ID_PEKERJAAN != value))
				{
					this._ID_PEKERJAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEKERJAAN", DbType="VarChar(50)")]
		public string PEKERJAAN
		{
			get
			{
				return this._PEKERJAAN;
			}
			set
			{
				if ((this._PEKERJAAN != value))
				{
					this._PEKERJAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SEAM", DbType="Int")]
		public System.Nullable<int> ID_SEAM
		{
			get
			{
				return this._ID_SEAM;
			}
			set
			{
				if ((this._ID_SEAM != value))
				{
					this._ID_SEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEAM", DbType="VarChar(50)")]
		public string SEAM
		{
			get
			{
				return this._SEAM;
			}
			set
			{
				if ((this._SEAM != value))
				{
					this._SEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOLUME", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> VOLUME
		{
			get
			{
				return this._VOLUME;
			}
			set
			{
				if ((this._VOLUME != value))
				{
					this._VOLUME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_WORK_HOUR", DbType="DateTime")]
		public System.Nullable<System.DateTime> START_WORK_HOUR
		{
			get
			{
				return this._START_WORK_HOUR;
			}
			set
			{
				if ((this._START_WORK_HOUR != value))
				{
					this._START_WORK_HOUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_H", DbType="Int")]
		public System.Nullable<int> TIME_H
		{
			get
			{
				return this._TIME_H;
			}
			set
			{
				if ((this._TIME_H != value))
				{
					this._TIME_H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_M", DbType="Int")]
		public System.Nullable<int> TIME_M
		{
			get
			{
				return this._TIME_M;
			}
			set
			{
				if ((this._TIME_M != value))
				{
					this._TIME_M = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NILAI", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> NILAI
		{
			get
			{
				return this._NILAI;
			}
			set
			{
				if ((this._NILAI != value))
				{
					this._NILAI = value;
				}
			}
		}
	}
	
	public partial class cufn_getDetailOperatorResult
	{
		
		private int _ID;
		
		private string _OPERATOR;
		
		private string _NAMA;
		
		private System.Nullable<int> _ID_EQUIPMENT;
		
		private string _EQUIPMENT;
		
		private System.Nullable<int> _ID_PEKERJAAN;
		
		private string _NAMA_PEKERJAAN;
		
		private System.Nullable<int> _ID_SEAM;
		
		private string _NAMA_SEAM;
		
		private System.Nullable<decimal> _VOLUME;
		
		private System.Nullable<System.DateTime> _START_WORK_HOUR;
		
		private System.Nullable<int> _TIME_H;
		
		private System.Nullable<int> _TIME_M;
		
		private System.Nullable<int> _STATUS;
		
		public cufn_getDetailOperatorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATOR", DbType="VarChar(20)")]
		public string OPERATOR
		{
			get
			{
				return this._OPERATOR;
			}
			set
			{
				if ((this._OPERATOR != value))
				{
					this._OPERATOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(150)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EQUIPMENT", DbType="Int")]
		public System.Nullable<int> ID_EQUIPMENT
		{
			get
			{
				return this._ID_EQUIPMENT;
			}
			set
			{
				if ((this._ID_EQUIPMENT != value))
				{
					this._ID_EQUIPMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT", DbType="VarChar(50)")]
		public string EQUIPMENT
		{
			get
			{
				return this._EQUIPMENT;
			}
			set
			{
				if ((this._EQUIPMENT != value))
				{
					this._EQUIPMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEKERJAAN", DbType="Int")]
		public System.Nullable<int> ID_PEKERJAAN
		{
			get
			{
				return this._ID_PEKERJAAN;
			}
			set
			{
				if ((this._ID_PEKERJAAN != value))
				{
					this._ID_PEKERJAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_PEKERJAAN", DbType="VarChar(50)")]
		public string NAMA_PEKERJAAN
		{
			get
			{
				return this._NAMA_PEKERJAAN;
			}
			set
			{
				if ((this._NAMA_PEKERJAAN != value))
				{
					this._NAMA_PEKERJAAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SEAM", DbType="Int")]
		public System.Nullable<int> ID_SEAM
		{
			get
			{
				return this._ID_SEAM;
			}
			set
			{
				if ((this._ID_SEAM != value))
				{
					this._ID_SEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_SEAM", DbType="VarChar(50)")]
		public string NAMA_SEAM
		{
			get
			{
				return this._NAMA_SEAM;
			}
			set
			{
				if ((this._NAMA_SEAM != value))
				{
					this._NAMA_SEAM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VOLUME", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> VOLUME
		{
			get
			{
				return this._VOLUME;
			}
			set
			{
				if ((this._VOLUME != value))
				{
					this._VOLUME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_START_WORK_HOUR", DbType="DateTime")]
		public System.Nullable<System.DateTime> START_WORK_HOUR
		{
			get
			{
				return this._START_WORK_HOUR;
			}
			set
			{
				if ((this._START_WORK_HOUR != value))
				{
					this._START_WORK_HOUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_H", DbType="Int")]
		public System.Nullable<int> TIME_H
		{
			get
			{
				return this._TIME_H;
			}
			set
			{
				if ((this._TIME_H != value))
				{
					this._TIME_H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME_M", DbType="Int")]
		public System.Nullable<int> TIME_M
		{
			get
			{
				return this._TIME_M;
			}
			set
			{
				if ((this._TIME_M != value))
				{
					this._TIME_M = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
