<?xml version="1.0" encoding="utf-8"?><Database Name="DB_ENG_ECOAL_MASS_KPT" Class="db_eCoalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=kphosq101\shpol;Initial Catalog=DB_ENG_ECOAL_MASS_KPT;User ID=sqlservices" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_ENG_ECOAL_MASS_KPTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_M_PROFILE" Member="TBL_M_PROFILEs">
    <Type Name="TBL_M_PROFILE">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PROFILE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_M_PEKERJAAN" Member="TBL_M_PEKERJAANs">
    <Type Name="TBL_M_PEKERJAAN">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAMA_PEKERJAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_M_SEAM" Member="TBL_M_SEAMs">
    <Type Name="TBL_M_SEAM">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAMA_SEAM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_T_PAIRING_OPERATOR_UNIT" Member="TBL_T_PAIRING_OPERATOR_UNITs">
    <Type Name="TBL_T_PAIRING_OPERATOR_UNIT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OPERATOR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ID_EQUIPMENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQUIPMENT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_PEKERJAAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_SEAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VOLUME" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="START_WORK_HOUR" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TIME_H" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIME_M" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIME_S" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GRADE" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="INPUT_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INPUT_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.cufn_getAlatByPekerjanSeam" Method="cufn_getAlatByPekerjanSeam" IsComposable="true">
    <Parameter Name="PEKERJAAN" Parameter="pEKERJAAN" Type="System.Int32" DbType="Int" />
    <Parameter Name="SEAM" Parameter="sEAM" Type="System.Int32" DbType="Int" />
    <ElementType Name="cufn_getAlatByPekerjanSeamResult">
      <Column Name="ID_MAPPING" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_SEAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAMA_SEAM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_ALAT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAMA_ALAT" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PROTY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.cufn_getListOperatorByRating" Method="cufn_getListOperatorByRating" IsComposable="true">
    <Parameter Name="PEKERJAAN" Parameter="pEKERJAAN" Type="System.Int32" DbType="Int" />
    <ElementType Name="cufn_getListOperatorByRatingResult">
      <Column Name="NRP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAMA" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SUBCONT_CODE" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ID_JABATAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JABATAN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DISTRICT" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ID_PEKERJAAN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAMA_PEKERJAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AVG_AP" Type="System.Decimal" DbType="Decimal(38,6) NOT NULL" CanBeNull="false" />
      <Column Name="STATUS_AVALIABLE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.cusp_getListPenilaian" Method="cusp_getListPenilaian">
    <ElementType Name="cusp_getListPenilaianResult">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OPERATOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ID_EQUIPMENT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQUIPMENT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_PEKERJAAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PEKERJAAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_SEAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEAM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VOLUME" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="START_WORK_HOUR" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TIME_H" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIME_M" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NILAI" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>